FROM node:18-alpine

WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies including development dependencies
RUN npm install

# Copy application code
COPY . .

# Expose the application port
EXPOSE 5000

# Run the application in development mode with nodemon
CMD ["npm", "run", "dev"]
