version: '3.8'

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/horsey-backend:latest
    container_name: horsey-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://horsey_user:horsey_password@mongodb:27017/horsey
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - LICHESS_CLIENT_ID=${LICHESS_CLIENT_ID}
      - LICHESS_CLIENT_SECRET=${LICHESS_CLIENT_SECRET}
      - LICHESS_REDIRECT_URI=${LICHESS_REDIRECT_URI}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - INITIAL_ADMIN_USERNAME=${INITIAL_ADMIN_USERNAME}
      - INITIAL_ADMIN_EMAIL=${INITIAL_ADMIN_EMAIL}
      - INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - mongodb
    networks:
      - horsey-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    image: ${DOCKERHUB_USERNAME}/horsey-frontend:latest
    container_name: horsey-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - REACT_APP_API_URL=https://api.yourdomainname.com
      - REACT_APP_LICHESS_REDIRECT_URI=${LICHESS_REDIRECT_URI}
    depends_on:
      - backend
    volumes:
      - ./ssl:/etc/nginx/ssl
    networks:
      - horsey-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_APP_USERNAME=horsey_user
      - MONGO_APP_PASSWORD=horsey_password
    networks:
      - horsey-network
    command: [--auth]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  horsey-network:
    driver: bridge

volumes:
  mongodb_data:
