global:
  scrape_interval: 60s
remote_write:
  - url: ${GRAFANA_CLOUD_PROMETHEUS_URL}
    basic_auth:
      username: ${GRAFANA_CLOUD_USERNAME}
      password: ${GRAFANA_CLOUD_SERVICE_ACCOUNT_TOKEN}
scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: horsey-backend
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:5000"]
